services:
  # El servicio de base de datos que ya estaba funcionando
  postgres-db:
    image: postgres:15-alpine
    container_name: db_reservation
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: reservation-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # NUESTRO NUEVO SERVICIO BACKEND
  spring-backend:
    build: . # Le dice a Docker que busque el Dockerfile en la misma carpeta
    container_name: backend_reservation
    ports:
      - "8087:8087"
    depends_on:
      - postgres-db # El backend no arrancará hasta que la BD esté lista
    environment:
      # IMPORTANTE: Cambiamos 'localhost' por 'postgres-db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/reservation-db
      - DB_PASSWORD=admin123
      # Agrega tus variables de Mercado Pago y Cloudinary aquí
      - MP_ACCESS_TOKEN=APP_USR-930243329859387-033113-5eda1888650a4a3a494db03b37c7e91f-3264812537
      - CLOUDINARY_CLOUD_NAME=dbwq8gwxs
      - CLOUDINARY_API_KEY=396523953186898
      - CLOUDINARY_API_SECRET=vuUlEfpFtEmSBUwnWHaRxTSJlLA

volumes:
  postgres_data: