# --- BASE DE DATOS ---
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation-db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8087

# --- CONFIGURACIÓN DE CORREO (GMAIL) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CONFIGURACIÓN DE MERCADO PAGO ---
mercadopago.access-token=${MP_ACCESS_TOKEN}
mercadopago.public-key=${MP_PUBLIC_KEY}

# --- CONFIGURACIÓN DE CLOUDINARY ---
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# --- CONFIGURACIÓN DE SPRINGDOC SWAGGER ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=false

# --- URL DEL FRONTEND ---
app.frontend.base-url=http://localhost:5173