

spring.datasource.url=jdbc:postgresql://localhost:5432/reservation-db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8087

# --- CONFIGURACIÓN DE CORREO (GMAIL) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devjofrelautaro@gmail.com
spring.mail.password=suqk hiry eyoy vwrs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CONFIGURACIÓN DE CLOUDINARY ---
cloudinary.cloud_name=dbwq8gwxs
cloudinary.api_key=396523953186898
cloudinary.api_secret=vuUlEfpFtEmSBUwnWHaRxTSJlLA