# --- BASE DE DATOS ---
spring.datasource.url=jdbc:postgresql://localhost:5432/reservation-db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8087

# --- CONFIGURACIÓN DE CORREO (GMAIL) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CONFIGURACIÓN DE MERCADO PAGO ---
mercadopago.access-token=${MP_ACCESS_TOKEN}
mercadopago.public-key=${MP_PUBLIC_KEY}

# --- CONFIGURACIÓN DE CLOUDINARY ---
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# --- CONFIGURACIÓN DE SPRINGDOC SWAGGER ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=false

# --- CONFIGURACIÓN DE CACHE ---
# --- CONFIGURACIÓN DE CACHE ---
spring.data.redis.host=capital-eft-117737.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAACvpAAIgcDFiZDU4YmFhYmM4OGM0NzgxYWRkYjIyYzVhNjMzZmEyYg
spring.data.redis.ssl.enabled=true
# --- URL DEL FRONTEND ---
app.frontend.base-url=https://devcursos-lj.vercel.app/

# ========================================================
# OPTIMIZACIÓN PARA BASE DE DATOS SERVERLESS EN LA NUBE (NEON)
# ========================================================

# Evita que Hikari guarde conexiones muertas. Neon suele cortar a los 5 mins.
# Le decimos a Hikari que mate la conexión a los 4 minutos (240000 ms) por las dudas.
spring.datasource.hikari.max-lifetime=240000

# Le hace "ping" a la base de datos cada 30 segundos para que Neon no la apague tan rápido.
spring.datasource.hikari.keepalive-time=30000

# Mantiene un pool de conexiones chiquito para no saturar los límites gratuitos.
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=10

# Tiempo máximo que espera Spring si la base de datos tarda en despertar (30 segundos).
spring.datasource.hikari.connection-timeout=30000

# SENTRY CONFIG
# La llave que copiaste en el paso 1 (Si es nulo o vacío, Sentry se apaga automáticamente, ideal para local)
sentry.dsn=${SENTRY_DSN:} 

# Qué porcentaje de errores queremos capturar (1.0 = 100%)
sentry.traces-sample-rate=1.0

# Para saber en qué entorno estamos
sentry.environment=production