name: DevCursos Backend CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    name: Compilar y Ejecutar Tests
    runs-on: ubuntu-latest

    # 👇 ESTA ES LA CLAVE: Le decimos al robot que entre a la carpeta del backend
    defaults:
      run:
        working-directory: ./reservation-backend

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Configurar Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17' 
        distribution: 'temurin'
        cache: 'maven'

    - name: Dar permisos al Maven Wrapper
      run: chmod +x mvnw

    - name: Ejecutar Tests
      run: ./mvnw test